package session;

public enum SessionStatus {
    INITIAL,
    WAITING_FOR_INITIAL_DEPOSIT_INPUT,
    HAS_INITIAL_DEPOSIT_VALUE,
    WAITING_TO_DOWNLOAD_COINS_LIST,
    COINS_LIST_DOWNLOADED,
    WAITING_FOR_WEB_SOCKETS_CONNECTION,
    CONNECTED_TO_WEB_SOCKETS,
    WAITING_FOR_SPREAD_SIGNAL
}
